// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from common.proto</summary>
public static partial class CommonReflection {

  #region Descriptor
  /// <summary>File descriptor for common.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CommonReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgxjb21tb24ucHJvdG8iaQoQU2VydmVyU2VuZEluZm9fdBIQCghzdGVhbV9p",
          "ZBgBIAEoBBIOCgZzZWN1cmUYAiABKAgSEAoIaG9zdG5hbWUYAyABKAkSDwoH",
          "bWFwbmFtZRgEIAEoCRIQCghnYW1ldHlwZRgFIAEoCSIqChpTZXJ2ZXJQYXNz",
          "QXV0aGVudGljYXRpb25fdBIMCgRkYXRhGAEgASgNIioKGlNlcnZlckZhaWxB",
          "dXRoZW50aWNhdGlvbl90EgwKBGRhdGEYASABKA0iQgobQ2xpZW50QmVnaW5B",
          "dXRoZW50aWNhdGlvbl90EhQKDHRva2VuX2xlbmd0aBgBIAEoDRINCgV0b2tl",
          "bhgCIAEoDCKHAgoLR2FtZU1lc3NhZ2USKwoOU2VydmVyU2VuZEluZm8YASAB",
          "KAsyES5TZXJ2ZXJTZW5kSW5mb190SAASPwoYU2VydmVyUGFzc0F1dGhlbnRp",
          "Y2F0aW9uGAIgASgLMhsuU2VydmVyUGFzc0F1dGhlbnRpY2F0aW9uX3RIABI/",
          "ChhTZXJ2ZXJGYWlsQXV0aGVudGljYXRpb24YAyABKAsyGy5TZXJ2ZXJGYWls",
          "QXV0aGVudGljYXRpb25fdEgAEkEKGUNsaWVudEJlZ2luQXV0aGVudGljYXRp",
          "b24YBCABKAsyHC5DbGllbnRCZWdpbkF1dGhlbnRpY2F0aW9uX3RIAEIGCgR0",
          "eXBlYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ServerSendInfo_t), global::ServerSendInfo_t.Parser, new[]{ "SteamId", "Secure", "Hostname", "Mapname", "Gametype" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ServerPassAuthentication_t), global::ServerPassAuthentication_t.Parser, new[]{ "Data" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ServerFailAuthentication_t), global::ServerFailAuthentication_t.Parser, new[]{ "Data" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ClientBeginAuthentication_t), global::ClientBeginAuthentication_t.Parser, new[]{ "TokenLength", "Token" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GameMessage), global::GameMessage.Parser, new[]{ "ServerSendInfo", "ServerPassAuthentication", "ServerFailAuthentication", "ClientBeginAuthentication" }, new[]{ "Type" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ServerSendInfo_t : pb::IMessage<ServerSendInfo_t>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ServerSendInfo_t> _parser = new pb::MessageParser<ServerSendInfo_t>(() => new ServerSendInfo_t());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ServerSendInfo_t> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerSendInfo_t() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerSendInfo_t(ServerSendInfo_t other) : this() {
    steamId_ = other.steamId_;
    secure_ = other.secure_;
    hostname_ = other.hostname_;
    mapname_ = other.mapname_;
    gametype_ = other.gametype_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerSendInfo_t Clone() {
    return new ServerSendInfo_t(this);
  }

  /// <summary>Field number for the "steam_id" field.</summary>
  public const int SteamIdFieldNumber = 1;
  private ulong steamId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong SteamId {
    get { return steamId_; }
    set {
      steamId_ = value;
    }
  }

  /// <summary>Field number for the "secure" field.</summary>
  public const int SecureFieldNumber = 2;
  private bool secure_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Secure {
    get { return secure_; }
    set {
      secure_ = value;
    }
  }

  /// <summary>Field number for the "hostname" field.</summary>
  public const int HostnameFieldNumber = 3;
  private string hostname_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Hostname {
    get { return hostname_; }
    set {
      hostname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "mapname" field.</summary>
  public const int MapnameFieldNumber = 4;
  private string mapname_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Mapname {
    get { return mapname_; }
    set {
      mapname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "gametype" field.</summary>
  public const int GametypeFieldNumber = 5;
  private string gametype_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Gametype {
    get { return gametype_; }
    set {
      gametype_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ServerSendInfo_t);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ServerSendInfo_t other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SteamId != other.SteamId) return false;
    if (Secure != other.Secure) return false;
    if (Hostname != other.Hostname) return false;
    if (Mapname != other.Mapname) return false;
    if (Gametype != other.Gametype) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SteamId != 0UL) hash ^= SteamId.GetHashCode();
    if (Secure != false) hash ^= Secure.GetHashCode();
    if (Hostname.Length != 0) hash ^= Hostname.GetHashCode();
    if (Mapname.Length != 0) hash ^= Mapname.GetHashCode();
    if (Gametype.Length != 0) hash ^= Gametype.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SteamId != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(SteamId);
    }
    if (Secure != false) {
      output.WriteRawTag(16);
      output.WriteBool(Secure);
    }
    if (Hostname.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Hostname);
    }
    if (Mapname.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Mapname);
    }
    if (Gametype.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Gametype);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SteamId != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(SteamId);
    }
    if (Secure != false) {
      output.WriteRawTag(16);
      output.WriteBool(Secure);
    }
    if (Hostname.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Hostname);
    }
    if (Mapname.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Mapname);
    }
    if (Gametype.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Gametype);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SteamId != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SteamId);
    }
    if (Secure != false) {
      size += 1 + 1;
    }
    if (Hostname.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Hostname);
    }
    if (Mapname.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Mapname);
    }
    if (Gametype.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Gametype);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ServerSendInfo_t other) {
    if (other == null) {
      return;
    }
    if (other.SteamId != 0UL) {
      SteamId = other.SteamId;
    }
    if (other.Secure != false) {
      Secure = other.Secure;
    }
    if (other.Hostname.Length != 0) {
      Hostname = other.Hostname;
    }
    if (other.Mapname.Length != 0) {
      Mapname = other.Mapname;
    }
    if (other.Gametype.Length != 0) {
      Gametype = other.Gametype;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SteamId = input.ReadUInt64();
          break;
        }
        case 16: {
          Secure = input.ReadBool();
          break;
        }
        case 26: {
          Hostname = input.ReadString();
          break;
        }
        case 34: {
          Mapname = input.ReadString();
          break;
        }
        case 42: {
          Gametype = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          SteamId = input.ReadUInt64();
          break;
        }
        case 16: {
          Secure = input.ReadBool();
          break;
        }
        case 26: {
          Hostname = input.ReadString();
          break;
        }
        case 34: {
          Mapname = input.ReadString();
          break;
        }
        case 42: {
          Gametype = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ServerPassAuthentication_t : pb::IMessage<ServerPassAuthentication_t>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ServerPassAuthentication_t> _parser = new pb::MessageParser<ServerPassAuthentication_t>(() => new ServerPassAuthentication_t());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ServerPassAuthentication_t> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerPassAuthentication_t() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerPassAuthentication_t(ServerPassAuthentication_t other) : this() {
    data_ = other.data_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerPassAuthentication_t Clone() {
    return new ServerPassAuthentication_t(this);
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 1;
  private uint data_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Data {
    get { return data_; }
    set {
      data_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ServerPassAuthentication_t);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ServerPassAuthentication_t other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Data != other.Data) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Data != 0) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Data != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Data != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Data != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ServerPassAuthentication_t other) {
    if (other == null) {
      return;
    }
    if (other.Data != 0) {
      Data = other.Data;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Data = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Data = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ServerFailAuthentication_t : pb::IMessage<ServerFailAuthentication_t>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ServerFailAuthentication_t> _parser = new pb::MessageParser<ServerFailAuthentication_t>(() => new ServerFailAuthentication_t());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ServerFailAuthentication_t> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerFailAuthentication_t() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerFailAuthentication_t(ServerFailAuthentication_t other) : this() {
    data_ = other.data_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerFailAuthentication_t Clone() {
    return new ServerFailAuthentication_t(this);
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 1;
  private uint data_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Data {
    get { return data_; }
    set {
      data_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ServerFailAuthentication_t);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ServerFailAuthentication_t other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Data != other.Data) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Data != 0) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Data != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Data != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Data != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ServerFailAuthentication_t other) {
    if (other == null) {
      return;
    }
    if (other.Data != 0) {
      Data = other.Data;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Data = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Data = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ClientBeginAuthentication_t : pb::IMessage<ClientBeginAuthentication_t>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ClientBeginAuthentication_t> _parser = new pb::MessageParser<ClientBeginAuthentication_t>(() => new ClientBeginAuthentication_t());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ClientBeginAuthentication_t> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ClientBeginAuthentication_t() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ClientBeginAuthentication_t(ClientBeginAuthentication_t other) : this() {
    tokenLength_ = other.tokenLength_;
    token_ = other.token_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ClientBeginAuthentication_t Clone() {
    return new ClientBeginAuthentication_t(this);
  }

  /// <summary>Field number for the "token_length" field.</summary>
  public const int TokenLengthFieldNumber = 1;
  private uint tokenLength_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint TokenLength {
    get { return tokenLength_; }
    set {
      tokenLength_ = value;
    }
  }

  /// <summary>Field number for the "token" field.</summary>
  public const int TokenFieldNumber = 2;
  private pb::ByteString token_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Token {
    get { return token_; }
    set {
      token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ClientBeginAuthentication_t);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ClientBeginAuthentication_t other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (TokenLength != other.TokenLength) return false;
    if (Token != other.Token) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (TokenLength != 0) hash ^= TokenLength.GetHashCode();
    if (Token.Length != 0) hash ^= Token.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (TokenLength != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(TokenLength);
    }
    if (Token.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(Token);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (TokenLength != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(TokenLength);
    }
    if (Token.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(Token);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (TokenLength != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TokenLength);
    }
    if (Token.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Token);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ClientBeginAuthentication_t other) {
    if (other == null) {
      return;
    }
    if (other.TokenLength != 0) {
      TokenLength = other.TokenLength;
    }
    if (other.Token.Length != 0) {
      Token = other.Token;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          TokenLength = input.ReadUInt32();
          break;
        }
        case 18: {
          Token = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          TokenLength = input.ReadUInt32();
          break;
        }
        case 18: {
          Token = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class GameMessage : pb::IMessage<GameMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GameMessage> _parser = new pb::MessageParser<GameMessage>(() => new GameMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GameMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameMessage(GameMessage other) : this() {
    switch (other.TypeCase) {
      case TypeOneofCase.ServerSendInfo:
        ServerSendInfo = other.ServerSendInfo.Clone();
        break;
      case TypeOneofCase.ServerPassAuthentication:
        ServerPassAuthentication = other.ServerPassAuthentication.Clone();
        break;
      case TypeOneofCase.ServerFailAuthentication:
        ServerFailAuthentication = other.ServerFailAuthentication.Clone();
        break;
      case TypeOneofCase.ClientBeginAuthentication:
        ClientBeginAuthentication = other.ClientBeginAuthentication.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameMessage Clone() {
    return new GameMessage(this);
  }

  /// <summary>Field number for the "ServerSendInfo" field.</summary>
  public const int ServerSendInfoFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ServerSendInfo_t ServerSendInfo {
    get { return typeCase_ == TypeOneofCase.ServerSendInfo ? (global::ServerSendInfo_t) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.ServerSendInfo;
    }
  }

  /// <summary>Field number for the "ServerPassAuthentication" field.</summary>
  public const int ServerPassAuthenticationFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ServerPassAuthentication_t ServerPassAuthentication {
    get { return typeCase_ == TypeOneofCase.ServerPassAuthentication ? (global::ServerPassAuthentication_t) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.ServerPassAuthentication;
    }
  }

  /// <summary>Field number for the "ServerFailAuthentication" field.</summary>
  public const int ServerFailAuthenticationFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ServerFailAuthentication_t ServerFailAuthentication {
    get { return typeCase_ == TypeOneofCase.ServerFailAuthentication ? (global::ServerFailAuthentication_t) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.ServerFailAuthentication;
    }
  }

  /// <summary>Field number for the "ClientBeginAuthentication" field.</summary>
  public const int ClientBeginAuthenticationFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ClientBeginAuthentication_t ClientBeginAuthentication {
    get { return typeCase_ == TypeOneofCase.ClientBeginAuthentication ? (global::ClientBeginAuthentication_t) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.ClientBeginAuthentication;
    }
  }

  private object type_;
  /// <summary>Enum of possible cases for the "type" oneof.</summary>
  public enum TypeOneofCase {
    None = 0,
    ServerSendInfo = 1,
    ServerPassAuthentication = 2,
    ServerFailAuthentication = 3,
    ClientBeginAuthentication = 4,
  }
  private TypeOneofCase typeCase_ = TypeOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TypeOneofCase TypeCase {
    get { return typeCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearType() {
    typeCase_ = TypeOneofCase.None;
    type_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GameMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GameMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(ServerSendInfo, other.ServerSendInfo)) return false;
    if (!object.Equals(ServerPassAuthentication, other.ServerPassAuthentication)) return false;
    if (!object.Equals(ServerFailAuthentication, other.ServerFailAuthentication)) return false;
    if (!object.Equals(ClientBeginAuthentication, other.ClientBeginAuthentication)) return false;
    if (TypeCase != other.TypeCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (typeCase_ == TypeOneofCase.ServerSendInfo) hash ^= ServerSendInfo.GetHashCode();
    if (typeCase_ == TypeOneofCase.ServerPassAuthentication) hash ^= ServerPassAuthentication.GetHashCode();
    if (typeCase_ == TypeOneofCase.ServerFailAuthentication) hash ^= ServerFailAuthentication.GetHashCode();
    if (typeCase_ == TypeOneofCase.ClientBeginAuthentication) hash ^= ClientBeginAuthentication.GetHashCode();
    hash ^= (int) typeCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (typeCase_ == TypeOneofCase.ServerSendInfo) {
      output.WriteRawTag(10);
      output.WriteMessage(ServerSendInfo);
    }
    if (typeCase_ == TypeOneofCase.ServerPassAuthentication) {
      output.WriteRawTag(18);
      output.WriteMessage(ServerPassAuthentication);
    }
    if (typeCase_ == TypeOneofCase.ServerFailAuthentication) {
      output.WriteRawTag(26);
      output.WriteMessage(ServerFailAuthentication);
    }
    if (typeCase_ == TypeOneofCase.ClientBeginAuthentication) {
      output.WriteRawTag(34);
      output.WriteMessage(ClientBeginAuthentication);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (typeCase_ == TypeOneofCase.ServerSendInfo) {
      output.WriteRawTag(10);
      output.WriteMessage(ServerSendInfo);
    }
    if (typeCase_ == TypeOneofCase.ServerPassAuthentication) {
      output.WriteRawTag(18);
      output.WriteMessage(ServerPassAuthentication);
    }
    if (typeCase_ == TypeOneofCase.ServerFailAuthentication) {
      output.WriteRawTag(26);
      output.WriteMessage(ServerFailAuthentication);
    }
    if (typeCase_ == TypeOneofCase.ClientBeginAuthentication) {
      output.WriteRawTag(34);
      output.WriteMessage(ClientBeginAuthentication);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (typeCase_ == TypeOneofCase.ServerSendInfo) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServerSendInfo);
    }
    if (typeCase_ == TypeOneofCase.ServerPassAuthentication) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServerPassAuthentication);
    }
    if (typeCase_ == TypeOneofCase.ServerFailAuthentication) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServerFailAuthentication);
    }
    if (typeCase_ == TypeOneofCase.ClientBeginAuthentication) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClientBeginAuthentication);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GameMessage other) {
    if (other == null) {
      return;
    }
    switch (other.TypeCase) {
      case TypeOneofCase.ServerSendInfo:
        if (ServerSendInfo == null) {
          ServerSendInfo = new global::ServerSendInfo_t();
        }
        ServerSendInfo.MergeFrom(other.ServerSendInfo);
        break;
      case TypeOneofCase.ServerPassAuthentication:
        if (ServerPassAuthentication == null) {
          ServerPassAuthentication = new global::ServerPassAuthentication_t();
        }
        ServerPassAuthentication.MergeFrom(other.ServerPassAuthentication);
        break;
      case TypeOneofCase.ServerFailAuthentication:
        if (ServerFailAuthentication == null) {
          ServerFailAuthentication = new global::ServerFailAuthentication_t();
        }
        ServerFailAuthentication.MergeFrom(other.ServerFailAuthentication);
        break;
      case TypeOneofCase.ClientBeginAuthentication:
        if (ClientBeginAuthentication == null) {
          ClientBeginAuthentication = new global::ClientBeginAuthentication_t();
        }
        ClientBeginAuthentication.MergeFrom(other.ClientBeginAuthentication);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::ServerSendInfo_t subBuilder = new global::ServerSendInfo_t();
          if (typeCase_ == TypeOneofCase.ServerSendInfo) {
            subBuilder.MergeFrom(ServerSendInfo);
          }
          input.ReadMessage(subBuilder);
          ServerSendInfo = subBuilder;
          break;
        }
        case 18: {
          global::ServerPassAuthentication_t subBuilder = new global::ServerPassAuthentication_t();
          if (typeCase_ == TypeOneofCase.ServerPassAuthentication) {
            subBuilder.MergeFrom(ServerPassAuthentication);
          }
          input.ReadMessage(subBuilder);
          ServerPassAuthentication = subBuilder;
          break;
        }
        case 26: {
          global::ServerFailAuthentication_t subBuilder = new global::ServerFailAuthentication_t();
          if (typeCase_ == TypeOneofCase.ServerFailAuthentication) {
            subBuilder.MergeFrom(ServerFailAuthentication);
          }
          input.ReadMessage(subBuilder);
          ServerFailAuthentication = subBuilder;
          break;
        }
        case 34: {
          global::ClientBeginAuthentication_t subBuilder = new global::ClientBeginAuthentication_t();
          if (typeCase_ == TypeOneofCase.ClientBeginAuthentication) {
            subBuilder.MergeFrom(ClientBeginAuthentication);
          }
          input.ReadMessage(subBuilder);
          ClientBeginAuthentication = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          global::ServerSendInfo_t subBuilder = new global::ServerSendInfo_t();
          if (typeCase_ == TypeOneofCase.ServerSendInfo) {
            subBuilder.MergeFrom(ServerSendInfo);
          }
          input.ReadMessage(subBuilder);
          ServerSendInfo = subBuilder;
          break;
        }
        case 18: {
          global::ServerPassAuthentication_t subBuilder = new global::ServerPassAuthentication_t();
          if (typeCase_ == TypeOneofCase.ServerPassAuthentication) {
            subBuilder.MergeFrom(ServerPassAuthentication);
          }
          input.ReadMessage(subBuilder);
          ServerPassAuthentication = subBuilder;
          break;
        }
        case 26: {
          global::ServerFailAuthentication_t subBuilder = new global::ServerFailAuthentication_t();
          if (typeCase_ == TypeOneofCase.ServerFailAuthentication) {
            subBuilder.MergeFrom(ServerFailAuthentication);
          }
          input.ReadMessage(subBuilder);
          ServerFailAuthentication = subBuilder;
          break;
        }
        case 34: {
          global::ClientBeginAuthentication_t subBuilder = new global::ClientBeginAuthentication_t();
          if (typeCase_ == TypeOneofCase.ClientBeginAuthentication) {
            subBuilder.MergeFrom(ClientBeginAuthentication);
          }
          input.ReadMessage(subBuilder);
          ClientBeginAuthentication = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
